turismoRealProject/applications/cliente/urls.py

from django.urls import path
from . import views

app_name="cliente_app"
urlpatterns = [
    path('',views.Inicio.as_view(),name='inicio-principal'),
    path('cliente/lista-departamentos/', views.ListaDepartamentosView.as_view(),name='lista_departamentos'),
    path('cliente/reserva-departamento/<id_departamento>', views.ReservarDepartamentoView.as_view(),name='reservar-departamento'),
    path('cliente/reservas/',views.ListaReservasView.as_view(),name='lista-reservas'),
    path('cliente/reservas/<id_reserva>',views.EditarReservaView,name='editar-reserva'),

    


]

turismoRealProject/applications/users/urls.py

from django.urls import path
from . import views

app_name="users_app"
urlpatterns = [
    #Clientes
    path('registro/', views.UserClienteRegisterView.as_view(),name='user-register'),
    path('login/', views.LoginUser.as_view(),name='user-login'),
    path('logout/', views.LogoutView.as_view(),name='user-logout'),
    #administrador
    path('loginAdmin/', views.LoginAdmin.as_view(),name='userAdmin-login'),
    #funcionario
    path('loginFuncionario/', views.LoginFuncionario.as_view(),name='userFuncionario-login'),
    path('logoutFuncionario/', views.LogoutFuncionarioView.as_view(),name='userFuncionario-logout'),


]

turismoRealProject/turismoRealProject/urls.py

from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header  =  "Custom bookstore admin"  
admin.site.site_title  =  "Custom bookstore admin site"
admin.site.index_title  =  "Custom Bookstore Admin"
urlpatterns = [
    path('jet/',include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.cliente.urls')),
    re_path('funcionario', include('applications.funcionario.urls')),
    re_path('',include('applications.reportesReserva.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

turismoRealProject/templates/sistemaCliente/detalle_pago_checkin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Pago reserva</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-4">
            <div class="card w-75">
                <div class="card-body">
                    <h5 class="card-title">{{reserva.id_departamento.nombre_departamento}}</h5>
                    
                    <form method="POST">
                        {%csrf_token%}
                        <p name="pago" class="card-text"> Precio a pagar </p>
                         <input type="text" disabled value="{{valor_pago}}">
                        <input type="hidden"  name="valor_pago" value="{{valor_pago}}" id="" >
                        <button   class="btn btn-danger" type="submit">Pagar checkin</button>
                    </form>

                </div>
            </div>
        </div>

    </div>

</body>

</html>

turismoRealProject/templates/sistemaCliente/detalle_pago_checkout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Pago reserva</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-4">
            <div class="card w-75">
                <div class="card-body">
                    <h5 class="card-title">{{reserva.id_departamento.nombre_departamento}}</h5>

                    <form method="POST">
                        {%csrf_token%}

                        {%if reserva.is_tour %}
                        {%if reserva.is_pago_tour%}
                        {%else%}
                        <h5>Tour por pagar</h5>
                        <p>Nombre Tour:{{reserva.id_departamento.id_tour.nombre_tour}}</p>
                        <p>Valor Tour:{{reserva.valor_tour}}</p>
                        {%endif%}
                        {%endif%}
                        {%if reserva.is_transporte%}
                        {%if reserva.is_pago_transporte%}
                        {%else%}
                        <h5>Transporte por Pagar</h5>
                        <p>Fecha ida {{reserva.id_transporte.fecha_ida}}</p>
                        <p>Fecha vuelta {{reserva.id_transporte.fecha_ida}}</p>
                        <p>Valor transporte {{reserva.valor_transporte}}</p>
                        {%endif%}
                        {%endif%}
                        <h5>items dañados por pagar</h5>
                        <ul>
                            {%for item in items%}
                            <li> {{item.nombre}}: {{item.precio_estimado}}</li>
                            {%endfor%}
                        </ul>
                        <p> precio total items {{precio_items}}</p>
                        <p> cantidad faltante {{por_pagar}}</p>
                        <hr>
                        <p> total <input disabled type="text" value="{{total}}"></p>
                        <input name="valor_pago" type="hidden" value="{{total}}"></p>

                        <button class="btn btn-danger" type="submit">Pagar checkout</button>


                    </form>

                </div>
            </div>
        </div>

    </div>

</body>

</html>

turismoRealProject/templates/sistemaCliente/detalle_pago_reserva.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Pago reserva</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center mt-4">
            <div class="card w-75">
                <div class="card-body">
                    <h5 class="card-title">{{reserva.id_departamento.nombre_departamento}}</h5>
                    
                    <form method="POST">
                        {%csrf_token%}
                        <p name="pago" class="card-text"> Precio a pagar </p>
                         <input type="text" disabled value="{{valor_pago}}">
                        <input type="hidden"  name="valor_pago" value="{{valor_pago}}" id="" >
                        <button   class="btn btn-danger" type="submit">Pagar checkin</button>
                    </form>

                </div>
            </div>
        </div>

    </div>

</body>

</html>

turismoRealProject/templates/sistemaCliente/editar_reserva.html
{% extends 'base/base.html'%}
{%load static %}
{%block titulo%}Ver Reserva{%endblock titulo%}
{%block contenido%}
{%include 'includes/nav.html' %}


<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 mt-4">
            <div class="card text-center">

                <div class="card-body">
                    <h5 class="card-title">{{reserva.id_departamento.nombre_departamento}}</h5>
                    <div class="row justify-content-center">
                        <div class="col-6">
                            <img class="img-fluid " src="{{reserva.id_departamento.imagen_departamento.url}}" alt="">
                        </div>

                    </div>
                    <div class="row mt-4 justify-content-center row-cols-1">
                        <div class="col-12 col-md-4 mb-3 ">
                            <label for="exampleFormControlInput1" class="form-label">Check In</label>
                            <input disabled value="{{reserva.id_check_in.fecha_checkin }}" type="email"
                                class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>
                        <div class="col-12 col-md-4 mb-3 ">
                            <label for="exampleFormControlInput1" class="form-label">Check Out</label>
                            <input disabled value="{{reserva.id_check_out.fecha_checkout}}" type="email"
                                class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <h4>Personas Extra</h4>
                        {%for persona in personas_extra %}
                        <div class="col-8 col-md-4 mb-3 ">
                            <input disabled value="{{persona.nombre}} {{persona.apellido}}" type="email"
                                class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>
                        {%endfor%}
                    </div>
                    <form method="POST" action="">
                        {%csrf_token%}
                        <div>
                            {%if personas_disponibles %}
                            <h4>Agregar persona extra</h4>
                            {%for persona_disponible in personas_disponibles%}
                            <div class="row mt-4 justify-content-center">

                                <div class="col-4 mb-3  ">
                                    <label for="exampleInputEmail1">Nombre</label>
                                    <input class="form-control" id='nombre{{persona_disponible}}'
                                        name="nombre{{persona_disponible}}" type="text">
                                </div>
                                <div class="col-4 mb-3 ">
                                    <label for="exampleInputEmail1">Apellido</label>
                                    <input class="form-control" id='apellido{{persona_disponible}}'
                                        name="apellido{{persona_disponible}}" type="text">
                                </div>
                            </div>
                            {%endfor%}
                            {%endif%}
                        </div>

                        <div>
                            {%if reserva.is_tour %}
                            <h4>Servicio de Tour</h4>
                            <div class="row mt-4 justify-content-center">

                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Nombre del tour:</label>
                                    <input disabled class="form-control"
                                        value="{{reserva.id_departamento.id_tour.nombre_tour}}" name="" type="text">
                                </div>
                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Valor total Tour:</label>
                                    <input disabled class="form-control" value=" ${{reserva.valor_tour}}" name=""
                                        type="text">
                                </div>
                            </div>
                            {%else%}
                            {%if reserva.id_departamento.is_tour%}
                            <h4 class="mt-4">Servicio de Tour</h4>
                            <div class="row mt-4 mb-4 justify-content-center ">
                                <div class="col-7">
                                    <input class="form-check-input" type="checkbox" value="0" name="tourCheck"
                                        id="tourCheck" onclick="tourCheckFunction()">
                                    <label class="form-check-label" for="flexCheckDefault">
                                        Seleccione esta casilla si quiere el servicio de tour
                                    </label>
                                </div>


                                <div class="col-5">
                                    <label class=" ms-2form-check-label" for="flexCheckDefault">
                                        Valor tour por persona : ${{reserva.id_departamento.id_tour.valor_tour}}
                                    </label>
                                </div>

                            </div>
                            {%endif%}
                            {%endif%}
                        </div>
                        <div>
                            {%if reserva.is_transporte%}
                            <h4>Servicio Transporte</h4>
                            <div class="row mt-4 justify-content-center">

                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Fecha ida:</label>
                                    <input disabled class="form-control" value="{{reserva.id_check_in.fecha_checkin }}"
                                        name="" type="text">
                                </div>
                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Fecha Vuelta:</label>
                                    <input disabled class="form-control" value=" {{reserva.id_check_out.fecha_checkout }}"
                                        name="" type="text">
                                </div>
                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Direccion Inicio</label>
                                    <input disabled class="form-control"
                                        value=" {{reserva.id_transporte.direccion_inicio}}" name="" type="text">
                                </div>
                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Nombre Chofer</label>
                                    <input disabled class="form-control"
                                        value=" {{reserva.id_transporte.id_sv_transporte.nombre_chofer}} {{reserva.id_transporte.id_sv_transporte.apellido_chofer}} "
                                        name="" type="text">
                                </div>
                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Patente</label>
                                    <input disabled class="form-control"
                                        value=" {{reserva.id_transporte.id_sv_transporte.patente_vehiculo}}" name=""
                                        type="text">
                                </div>
                                <div class="col-12 col-md-4 mb-3  ">
                                    <label for="exampleInputEmail1">Valor total</label>
                                    <input disabled class="form-control" value="${{reserva.valor_transporte}}" name=""
                                        type="text">
                                </div>
                            </div>
                            {%else%}
                            {%if reserva.id_departamento.is_transporte%}
                            <h4>Servicio Transporte</h4>
                            <div>
                                <div class="row justify-content-center">
                                    <div class=" col-md-6 mt-4 form-check">
                                        <input class="form-check-input" type="checkbox" value="0" id="transporteCheck"
                                            name="transporteCheck" onclick="transporteCheckFunction()">
                                        <label class=" ms-2 row form-check-label" for="flexCheckDefault1">
                                            Seleccione esta casilla si quiere el servicio de transporte
                                        </label>
                                    </div>

                                </div>


                                <div class="row justify-content-center">
                                    <div class="col-md-6">
                                        <label class=" ms-2 row form-check-label" for="flexCheckDefault">
                                            Valor transporte por persona :
                                            ${{reserva.id_departamento.id_sv_transporte.valor_transporte}}
                                        </label>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class=" mt-4 col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Ingrese su direccion de inicio</label>
                                            <input class="form-control" id='direccionInicioTransporte'
                                                name="direccionInicioTransporte" type="text">
                                            <p id="demo"></p>
                                        </div>
                                    </div>
                                    <div class=" mt-4 col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Direccion de llegada</label>
                                            <input class="form-control" disabled name="direccionInicioTransporte"
                                                type="text" disabled
                                                value="{{reserva.id_departamento.direccion_departamento}}">
                                        </div>
                                    </div>
                                    {{form.check_in}}
                                </div>
                            </div>
                            {%endif%}
                            {%endif%}
                        </div>
                        <div>
                            Por pagar
                            <div class="row justify-content-center ">
                                <div class=" mt-4 col-md-4">
                                    <div class="form-group">
                                        
                                        <input value="${{reserva.por_pagar}}" class="form-control" id='direccionInicioTransporte'
                                            name="direccionInicioTransporte" disabled type="text">
                                        <p id="demo"></p>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <button onclick="return validarDireccionInicio()" class="btn btn-success" type="submit">Actualizar
                            </button>
                    </form>

                    
                </div>

            </div>

        </div>

    </div>
</div>
<script>
    function tourCheckFunction() {
        // Get the checkbox
        var checkBox = document.getElementById("tourCheck");
        // Get the output text

        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            checkBox.value = true;

        } else {
            checkBox.value = false;
        }
    }

    function transporteCheckFunction() {
        // Get the checkbox
        var checkBox = document.getElementById("transporteCheck");
        // Get the output text

        // If the checkbox is checked, display the output text
        if (checkBox.checked == true) {
            checkBox.value = true;

        } else {
            checkBox.value = false;
        }
    }

    function validarDireccionInicio() {
        const transporte_check = document.querySelector('#transporteCheck')
        const direccion_inicio = document.querySelector('#direccionInicioTransporte')

        if (transporte_check.checked) {
            if (direccion_inicio.value.length <= 0) {
                text = "Ingrese una direccion "
                document.getElementById("demo").innerHTML = text;
                return false
            }
        } else {
            return true

        }

        return true
    }


</script>


{%endblock contenido%}

turismoRealProject/templates/sistemaCliente/inicio.html
{% extends 'base/base.html'%}
{%load static%}
{%block titulo%}Inicio{%endblock titulo%}


{%block contenido%}

{%include 'includes/nav.html' %}

<!-- Masthead-->

<div id="reservaAqui">

    <div class="container-fluid">
        <div class="row justify-content-center">
            <h1 style="color: white;" class="col-7 mt-4 text-center">Reserva tu departamento</h1>
        </div>

        {% if not user.is_anonymous %}
        <div class="row mt-4 justify-content-center">

            <a href="{% url 'cliente_app:lista_departamentos' %}" class="btn btn-primary col-7 col-md-2">Reserva
                aqui</a>

        </div>
        {%else%}
        <div class="row mt-4 justify-content-center">

            <a href="{% url 'users_app:user-login' %}" class="btn col-5 col-md-2 btn-primary">Reserva aqui</a>

        </div>

        {%endif%}
    </div>

</div>



<!-- Services-->
<section class="page-section" id="services">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Services</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="my-3">E-Commerce</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam
                    architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="my-3">Responsive Design</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam
                    architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="my-3">Web Security</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam
                    architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
        </div>
    </div>
</section>




<!-- Contact-->



{%endblock contenido%}

turismoRealProject/templates/sistemaCliente/lista_departamentos.html
{% extends 'base/base.html'%}
{%load static %}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}
{%include 'includes/nav.html' %}

<div class="container-fluid">

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="" method="GET">
        {% csrf_token %}
        
        <div class="row mt-4 justify-content-center">

            <div class="col-10 col-md-4 mt-2">
                <input id="comuna" name="comuna" class="form-control me-2" type="search" placeholder="A donde vas?"
                    aria-label="Buscar departamento">
            </div>

            <div class="col-10 col-md-4 mt-2">
                <input class="form-control me-2" type="search" placeholder="Numero de personas"
                    aria-label="Buscar departamento">
            </div>

            <button type="submit" class=" col-5 col-md-2 btn btn-primary mt-2">Buscar</button>
        </div>

        

    </form>




    <div class="mt-4 row justify-content-center">
        <div class="col-md-7">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th class=" col col-md-2" scope="col">Nombre departamento</th>
                            <th class=" col col-md-2" scope="col">Imagen</th>
                            <th class=" col col-md-2" scope="col">Capacidad</th>
                            <th class=" col col-md-2" scope="col">Valor/dia</th>
                            <th class="col" scope="col">Comuna</th>
                            <th class="col" scope="col">Tour</th>
                            <th class="col" scope="col">Transporte</th>
                            <th class="col" scope="col">Accion</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for d in departamentos %}
                        <tr>
                            <td class="col-md-2">{{d.nombre_departamento}}</td>
                            <td class="col-md-2">

                                {% if d.imagen_departamento %}
                                <img class="img-fluid " src="{{d.imagen_departamento.url}}" alt="">
                                {%else%}
                                <h1>Sin imagen</h1>
                                {%endif%}
                            </td>
                            <td class="col-md-2">{{d.numero_personas}} personas</td>
                            <td class="col-md-2">{{d.valor_dia}}</td>
                            <td class="col">{{d.id_zona}}</td>
                            {%if d.is_tour %}
                            <td class="col">Si</td>
                            {%else%}
                            <td class="col">No</td>
                            {%endif%}

                            {%if d.is_transporte %}
                            <td class="col">Si</td>
                            {%else%}
                            <td class="col">No</td>
                            {%endif%}
                            <td class="col"><a class="btn btn-success"
                                    href="{%url 'cliente_app:reservar-departamento' d.id_departamento %} ">Reservar</a>
                            </td>
                        </tr>
                        {%endfor%}

                    </tbody>
                </table>

            </div>

            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif%}

                    <li class="page-item"><a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}</a>
                    </li>

                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {%endif%}
                </ul>
            </nav>
            {%endif%}
        </div>

    </div>

</div>

{%endblock contenido%}
{%block footer%}
{% include 'includes/footer.html' %}
{%endblock footer%}

turismoRealProject/templates/sistemaCliente/lista_reservas.html
{% extends 'base/base.html'%}
{%load static %}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}
{%include 'includes/nav.html' %}


<div class="container">
  <h1 class="mt-4">Reservas </h1>

  <div class="table-responsive">

    <table class=" mt-4 table">
      <thead>
        <tr>
          <th scope="col">Fecha reserva</th>
          <th scope="col">Imagen</th>
          <th scope="col">Departamento</th>
          <th scope="col">Check In</th>
          <th scope="col">Check Out</th>
          <th scope="col">Comuna</th>
          <th scope="col">Valor Total</th>
          <th scope="col">Accion</th>

        </tr>
      </thead>
      <tbody>
        {% for r in reservas %}
        {% if r.is_pago_checkout %}
        {%else%}
        <tr>
          <th>{{r.fecha_reserva}}</th>
          <th class="col-md-2">
            {% if r.id_departamento.imagen_departamento %}
            <img class="img-fluid " src="{{r.id_departamento.imagen_departamento.url}}" alt="">
            {%else%}
            <h1>Sin imagen</h1>
            {%endif%}
          </th>
          <th>{{r.id_departamento.nombre_departamento}}</th>
          <td>{{r.id_check_in.fecha_checkin}}</td>
          <td>{{r.id_check_out.fecha_checkout}}</td>
          <td>{{r.id_departamento.id_zona.comuna}}</td>
          <td>${{r.valor_total }}</td>
          <td><a class="btn btn-success" href="{% url 'cliente_app:editar-reserva' r.id_reserva %}">Ver </a>

          </td>
        </tr>
        {%endif%}
        {%endfor%}
      </tbody>
    </table>
  </div>


  {% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Atras</a>
      </li>
      {% endif%}

      <li class="page-item"><a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}</a>
      </li>

      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a>
      </li>
      {%endif%}
    </ul>
  </nav>
  {%endif%}

</div>




{%endblock contenido%}

{%block footer%}
{% include 'includes/footer.html' %}
{%endblock footer%}