turismoRealProject/applications/cliente/urls.py

from django.urls import path
from . import views

app_name="cliente_app"
urlpatterns = [
    path('',views.Inicio.as_view(),name='inicio-principal'),
    path('cliente/lista-departamentos/', views.ListaDepartamentosView.as_view(),name='lista_departamentos'),
    path('cliente/reserva-departamento/<id_departamento>', views.ReservarDepartamentoView.as_view(),name='reservar-departamento'),
    path('cliente/reservas/',views.ListaReservasView.as_view(),name='lista-reservas'),
    path('cliente/reservas/<id_reserva>',views.EditarReservaView,name='editar-reserva'),

    


]

turismoRealProject/applications/users/urls.py

from django.urls import path
from . import views

app_name="users_app"
urlpatterns = [
    #Clientes
    path('registro/', views.UserClienteRegisterView.as_view(),name='user-register'),
    path('login/', views.LoginUser.as_view(),name='user-login'),
    path('logout/', views.LogoutView.as_view(),name='user-logout'),
    #administrador
    path('loginAdmin/', views.LoginAdmin.as_view(),name='userAdmin-login'),
    #funcionario
    path('loginFuncionario/', views.LoginFuncionario.as_view(),name='userFuncionario-login'),
    path('logoutFuncionario/', views.LogoutFuncionarioView.as_view(),name='userFuncionario-logout'),


]

turismoRealProject/turismoRealProject/urls.py

from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header  =  "Custom bookstore admin"  
admin.site.site_title  =  "Custom bookstore admin site"
admin.site.index_title  =  "Custom Bookstore Admin"
urlpatterns = [
    path('jet/',include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.cliente.urls')),
    re_path('funcionario', include('applications.funcionario.urls')),
    re_path('',include('applications.reportesReserva.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

turismoRealProject/templates/includes/footer.html
<!-- Footer-->

turismoRealProject/templates/includes/nav.html
{% load static%}
<div class="container-fluid">
    <div class="row navbar-dark bg-dark justify-content-center ">
        <div class="row justify-content-center">
    
            <li class="col-6 col-md-2 nav-item ">
                <a class="nav-link text-white" href="{% url 'cliente_app:inicio-principal' %}">
    
                    <img class="img-fluid" src="{% static '/img/logos/turismo_real_logo.png' %}" alt="">
                </a>
            </li>
        </div>
        <div class="row mb-4 justify-content-center">
            <li class="col-4 col-md-3 nav-item ">
                <a class="text-center nav-link text-white " href="#">Nosotros</a>
            </li>
            <li class="col-4 col-md-3 nav-item">
                <a class="text-center  nav-link text-white" href="#">Precios</a>
            </li>
            <li class="col-4 col-md-3 nav-item">
                <a class="text-center nav-link text-white" href="#">Contacto</a>
            </li>
        </div>
    
        {% if not user.is_anonymous %}
        <div class="row mb-4 justify-content-center">
            <div class="col-12">
                <h5 class="ms-4 text-center" style="color: white;">Bienvenido {{nombre_cliente}}</h5>
            </div>
        </div> 
        <div class="row justify-content-center">
            <div class="mb-4 col-5 col-lg-3 col-md-3 col-sm-5">
                <a style="color: white;" class="btn  btn-primary nav-link"
                    href="{% url 'cliente_app:lista-reservas' %}">Reservas</a>
            </div>
            <div class="mb-4 col-6 col-xxl-3 col-xl-3 col-lg-4 col-md-3 col-sm-5">
                <a style="color: white;" class="btn  btn-primary nav-link" href="{% url 'users_app:user-logout' %}">Cerrar
                    sesion</a>
            </div>
        </div>
        {%else%}
        <div class="row justify-content-center">
            <div class="row mb-4 justify-content-center">
                <div class="col-6 col-md-3">
                    <a style="color: white;" class="btn ml-4 btn-primary nav-link"
                        href="{% url 'users_app:user-login' %}">Iniciar sesion</a>
                </div>
                <div class="col-6 col-md-3">
                    <a style="color: white;" class="btn ml-4 btn-primary nav-link "
                        href="{% url 'users_app:user-register'%}">Crear Cuenta</a>
                </div>
            </div>
        </div>
        {%endif%}
    </div>
    
</div>