turismoRealProject/applications/funcionario/urls.py
from django.urls import path
from . import views

app_name="funcionario_app"
urlpatterns = [
    #Clientes
    path('/panel-Funcionario', views.FuncionarioPanelPrincialView.as_view(),name='panel-funcionario'),
    path('/listadoCliente', views.ListadoClientes.as_view(),name='listadoCliente'),
    path('/listadoItem/<slug:pk>', views.ListadoItem.as_view(),name='listadoItem'),
    path('/detalleCliente/<pk>', views.DetalleCliente.as_view(), name='cliente-detalle'),
    path('/modificarEstado', views.modificar_estado, name='modificar-estado'),
    path('/checkin', views.Checkin.as_view(), name='checkin'),
    path('/enviarCorrreoCheckin/<rut>/<id_reserva>', views.email_chekin, name='enviar-correo'),
    path('/pagarCheckin/<id_reserva>', views.pago_checkin, name='pago-checkin'),
    path('/enviarCorrreoCheckout/<rut>/<id_reserva>', views.email_chekout, name='enviar-correo2'),
    path('/enviarCorrreoCheckoutSinPagar/<rut>/<id_reserva>', views.email_chekout2, name='enviar-correo3'),

    path('/pagarCheckout/<id_reserva>', views.pago_checkout, name='pago-checkout'),




]

turismoRealProject/applications/users/urls.py

from django.urls import path
from . import views

app_name="users_app"
urlpatterns = [
    #Clientes
    path('registro/', views.UserClienteRegisterView.as_view(),name='user-register'),
    path('login/', views.LoginUser.as_view(),name='user-login'),
    path('logout/', views.LogoutView.as_view(),name='user-logout'),
    #administrador
    path('loginAdmin/', views.LoginAdmin.as_view(),name='userAdmin-login'),
    #funcionario
    path('loginFuncionario/', views.LoginFuncionario.as_view(),name='userFuncionario-login'),
    path('logoutFuncionario/', views.LogoutFuncionarioView.as_view(),name='userFuncionario-logout'),


]

turismoRealProject/turismoRealProject/urls.py

from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
admin.site.site_header  =  "Custom bookstore admin"  
admin.site.site_title  =  "Custom bookstore admin site"
admin.site.index_title  =  "Custom Bookstore Admin"
urlpatterns = [
    path('jet/',include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.cliente.urls')),
    re_path('funcionario', include('applications.funcionario.urls')),
    re_path('',include('applications.reportesReserva.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

turismoRealProject/applications/funcionario/models.py
from django.db import models
from applications.users.models import User
from applications.crudModelos.models import Departamento
class Funcionario(models.Model):
    
    nombre=models.CharField(max_length=50)
    apellido= models.CharField(max_length=50)
    user_cliente = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return " nombre:"+self.nombre+" "+self.apellido
    class Meta:
        verbose_name='Funcionario'




class Item(models.Model):
    ESTADO_CHOICES = [
    ('do', 'Daniado'),
    ('so', 'Sin observaciones'),
  
    ]
    nombre=models.CharField(max_length=40)
    descripcion =  models.TextField(max_length=200)
    estado= models.CharField(max_length=20,choices=ESTADO_CHOICES , default='so')
    id_departamento= models.ForeignKey(Departamento,on_delete=models.CASCADE)
    precio_estimado= models.PositiveIntegerField()
    fecha_registro= models.DateField(auto_now_add=True)

    def __str__(self):
        return "Nombre {}, Ubicado en departamento {}".format(self.nombre,self.id_departamento.numero_departamento) 


    

turismoRealProject/templates/sistemaFuncionario/checkin.html
{% extends 'base/base.html'%}
{%load static%}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}
<div class="container-fluid"> 
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="row justify-content-end collapse navbar-collapse" id="navbarNav">
        <ul class="col-md-2 navbar-nav ">
          <li class="nav-item mr-4 ">
            <a class="btn btn-primary" aria-current="page" href="{% url 'funcionario_app:checkin' %}">Adminitrar Pagos</a>
          </li>
          {% if not user.is_anonymous %}
          <li class="nav-item ml-4  ">
            <a class="btn btn-primary" aria-current="page" href="{% url 'users_app:userFuncionario-logout' %}">Cerrar sesion</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
<div class="content">
  <h1>Clientes</h1>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <form method='GET'>
    <input type='text' name='q' value='{{ request.GET.q }}'>
    <input class="btn btn-primary" type='submit' value="Buscar un cliente">

  </form>
  <h1>Check-in</h1>
  <h2>Cliente:</h2>

  <p>Nombre: {{ cliente.nombre }} {{ cliente.apellido }}</p>
  <p>Rut: {{ cliente.rut }}</p>
  <p>Fecha de nacimiento: {{ cliente.fecha_nacimiento }}</p>

  <h2>Reservas activas</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">reserva</th>
        <th scope="col">valor total</th>
        <th scope="col">nro departamento</th>
        <th scope="col">cantidad de personas </th>
        <th scope="col"> check-in </th>
        <th scope="col"> check-out </th>





      </tr>
    </thead>
    <tbody>
      {% for reserva in Reservas %}
      <tr>
        <th scope="row"> {{ forloop.counter }}</th>
        <td>{{ reserva.id_reserva }}</td>
        <td>{{ reserva.valor_total }}</td>
        <td>{{ reserva.id_departamento.numero_departamento }}</td>
        <td>{{ reserva.id_departamento.numero_personas }}</td>



        <td>{% if reserva.is_pago_checkin %}
          {%else%}<a class="btn btn-success"
            href="{% url 'funcionario_app:enviar-correo' rut=cliente.rut id_reserva=reserva.id_reserva %}"> solicitar
            pago</a>{%endif%} </td>


        

        
        <td>
          {% if reserva.is_pago_checkout %}
          {%else%}
              {% if reserva.por_pagar == 0 %}
              <a class="btn btn-success" href="{% url 'funcionario_app:enviar-correo3' rut=cliente.rut id_reserva=reserva.id_reserva %}">Finalizar Checkout </a>
              {%else%}
              <a class="btn btn-success" href="{% url 'funcionario_app:enviar-correo2' rut=cliente.rut id_reserva=reserva.id_reserva %}"> solicitar pago</a>
              {%endif%}
          {%endif%}
        </td>
        




        <!-- .0.user_cliente.id -->
      </tr>
      {% endfor %}
    </tbody>
  </table>


</div>





  {%endblock contenido%}

turismoRealProject/templates/sistemaFuncionario/detalle_cliente.html
{% extends 'base/base.html'%}
{%load static%}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}

<div class="content">

    <h1>{{ object.REse }}</h1>
    <h2>Cliente:</h2>

    <p>Nombre: {{ object.nombre }} {{ object.apellido }}</p>
    <p>Rut: {{ object.rut }}</p>
    <p>Fecha de nacimiento: {{ object.fecha_nacimiento }}</p>
    <h2>Reservas</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Reserva</th>
                <th scope="col">Valor total</th>
                <th scope="col">Departamento</th>
                <th scope="col">Numero</th>
                <th scope="col">Cantidad de personas</th>
                <th scope="col">Items</th>


            </tr>
        </thead>
        <tbody>
            {% for reserva in Reservas %}
            <tr>
                <th>{{ reserva.id_reserva }}</th>
                <td>{{ reserva.valor_total }}</td>
                <td>{{ reserva.id_departamento.nombre_departamento }}</td>
                <td>{{ reserva.id_departamento.numero_departamento }}</td>
                <td>{{ reserva.id_departamento.numero_personas }}</td>
                {%if reserva.is_pago_checkout%}
                {%else%}
                <td>
                    <form action="/funcionario/listadoItem/{{reserva.id_departamento.id_departamento}}" method="get">

                        <button type="submit" class="btn btn-primary"> Ver </button>
                    </form>
                </td>
                {%endif%}
            </tr>
            {% endfor %}


        </tbody>
    </table>

    <p>{{ Mensaje }}</p>

    <button class="btn btn-primary"> Volver</button>


</div>

{%endblock contenido%}

turismoRealProject/templates/sistemaFuncionario/index.html
{% extends 'base/base.html'%}
{%load static%}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}


<div class="container-fluid">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="row justify-content-end collapse navbar-collapse" id="navbarNav">
            <ul class="col-md-2 navbar-nav ">
              {% if not user.is_anonymous %}
              <li class="nav-item  ">
                <a class="btn btn-primary" aria-current="page" href="{% url 'users_app:userFuncionario-logout' %}">Cerrar sesion</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>


    <div class="row">
        <div class='col'>
            <h1>Bienvenido Funcionario:</h1>
        </div>
        
    </div>

    <div class="row mt-4 justify-content-center">
        <div class="col-md-4">
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Ingrese el cliente a buscar"
                    aria-label="Buscar departamento">
                <button class="btn btn-outline-success" type="submit">Buscar Cliente</button>
            </form>
        </div>
    </div>

    <div class="row mt-4 justify-content-center">
        <div class="col-md-6">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Verificar</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td><button type="button" class="btn btn-primary">Check-in</button>
                        <button type="button" class="btn btn-primary">Check-out</button>
                    </td>
                    
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td><button type="button" class="btn btn-primary">Check-in</button>
                        <button type="button" class="btn btn-primary">Check-out</button>
                    </td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td><button type="button" class="btn btn-primary">Check-in</button>
                        <button type="button" class="btn btn-primary">Check-out</button>
                    </td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>

{%endblock contenido%}

turismoRealProject/templates/sistemaFuncionario/listado_clientes.html
{% extends 'base/base.html'%}
{%load static%}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}
<div class="container-fluid"> 
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="row justify-content-end collapse navbar-collapse" id="navbarNav">
        <ul class="col-md-2 navbar-nav ">
          <li class="nav-item mr-4 ">
            <a class="btn btn-primary" aria-current="page" href="{% url 'funcionario_app:checkin' %}">Adminitrar Pagos</a>
          </li>
          {% if not user.is_anonymous %}
          <li class="nav-item ml-4  ">
            <a class="btn btn-primary" aria-current="page" href="{% url 'users_app:userFuncionario-logout' %}">Cerrar sesion</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  
<div class="content">
  <h1>Clientes</h1>
  <form method='GET'>
<input type='text' name='q' value='{{ request.GET.q }}'>
<input  class="btn btn-primary" type='submit' value="Buscar un cliente">

</form>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">rut</th>
      <th scope="col">Detalles del cliente</th>



      
    </tr>
  </thead>
  <tbody>
      {% if listado_clientes %}
      {% for cliente  in listado_clientes %}
    <tr>
      <th scope="row"> {{ forloop.counter }}</th>
      <td>{{cliente.nombre}}</td>
      <td>{{cliente.apellido}}</td>
      <td>{{cliente.rut}}</td>
      <td><a class="btn btn-primary mr-1 " href="{% url  'funcionario_app:cliente-detalle' pk=cliente.rut %}"> <i class="fas fa-eye "></i></a></td>


      
    </tr>
    {% endfor %}

    {% else %}
    <p>No hay cliente capichi.</p>
  {% endif %} 

  </tbody>
</table>
</div>


</div>


{%endblock contenido%}

turismoRealProject/templates/sistemaFuncionario/listado_items.html
{% extends 'base/base.html'%}
{%load static%}
{%block titulo%}Inicio{%endblock titulo%}

{%block contenido%}
<div class="content">
    <h1>Listado de items de departamento</h1>
    <form action="/funcionario/modificarEstado" method="post">
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">estado</th>
        <th scope="col">Nro.Departamento</th>
        <th scope="col">Precio estimado</th>        
        <th scope="col">Cambiar estado</th>



        
      </tr>
    </thead>
    <tbody>
        {% if items %}
        {% for item  in items %}
      <tr >
        <th scope="row"> {{ forloop.counter }}</th>
        <td>{{item.nombre}}</td>
        <td>{{item.get_estado_display}}</td>
        <td>{{item.id_departamento.numero_departamento}}</td>
        <td>{{item.precio_estimado}}</td>
        <input type="hidden" name="id_item" value="{{item.id}}" >

        <td>

        <select class="form-select" name="opciones"  aria-label="Default select example">
          {% for x, y in item.ESTADO_CHOICES %}
              <option value="{{ x }}"{% if item.estado == x %} selected{% endif %}>{{ y }}</option>
          {% endfor %}
        </select>
 

        </td>


        
      </tr>

     

      {% endfor %}

      {% else %}
    
    {% endif %} 
  
  </tbody>
</table>
<center> 
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary"> Guardar</button>
  </center>
</form>

</div>


{%endblock contenido%}

turismoRealProject/templates/sistemaFuncionario/template_correo_checkin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <h2>Estimado:</h2>
    <h2>{{nombre}} {{apellido}}</h2>
    <p>
    <a class="btn btn-primary"  href="http://localhost:8000/funcionario/pagarCheckin/{{id_reserva}}">Realizar pago de Checkin</a>
</body>

</html>

turismoRealProject/templates/sistemaFuncionario/template_correo_checkin2.html
<!--Plantilla utilizada: https://builder.dynamicxx.com/templates/121214/newview -->

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN""http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<base target="_blank">
<!-- Estilos global y responsivos-->
<style type="text/css">

body *{font-family: 'Open Sans', Arial, sans-serif }

div, p, a, li, td { -webkit-text-size-adjust:none; }

*{-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;}
td{word-break: break-word;}
a{word-break: break-word; text-decoration: none; color: inherit;}

body .ReadMsgBody
{width: 100%; background-color: #ffffff;}
body .ExternalClass
{width: 100%; background-color: #ffffff;}
body{width: 100%; height: 100%; background-color: #ffffff; margin:0; padding:0; -webkit-font-smoothing: antialiased;}
html{ background-color:#ffffff; width: 100%;}

body p {padding: 0!important; margin-top: 0!important; margin-right: 0!important; margin-bottom: 0!important; margin-left: 0!important; }
body img {user-drag: none; -moz-user-select: none; -webkit-user-drag: none;}
body .hover:hover {opacity:0.85;filter:alpha(opacity=85);}

body .image77 img {width: 77px; height: auto;}
body .icon18 img {width: 18px; height: auto;}
body .icon61 img {width: 61px; height: auto;}
body .logo img {width: 75px; height: auto;}
body .icon18 img {width: 18px; height: auto;}
body .circle-image img{width:104px; height:104px;}
body .full-size img{width:100%; height:auto;}

</style>

<style type="text/css">@media only screen and (max-width: 640px){
		body body{width:auto!important;}
		body table[class=full2] {width: 100%!important; clear: both; }
		body table[class=mobile2] {width: 100%!important; padding-left: 20px; padding-right: 20px; clear: both; }
		body table[class=fullCenter2] {width: 100%!important; text-align: center!important; clear: both; }
		body td[class=fullCenter2] {width: 100%!important; text-align: center!important; clear: both; }
		body td[class=pad15] {width: 100%!important; padding-left: 15px; padding-right: 15px; clear: both;}
}</style>

<style type="text/css">@media only screen and (max-width: 479px){
		body body{width:auto!important;}
		body table[class=full2] {width: 100%!important; clear: both; }
		body table[class=mobile2] {width: 100%!important; padding-left: 20px; padding-right: 20px; clear: both; }
		body table[class=fullCenter2] {width: 100%!important; text-align: center!important; clear: both; }
		body td[class=fullCenter2] {width: 100%!important; text-align: center!important; clear: both; }
		body table[class=full] {width: 100%!important; clear: both; }
		body table[class=mobile] {width: 100%!important; padding-left: 20px; padding-right: 20px; clear: both; }
		body table[class=fullCenter] {width: 100%!important; text-align: center!important; clear: both; }
		body td[class=fullCenter] {width: 100%!important; text-align: center!important; clear: both; }
		body td[class=pad15] {width: 100%!important; padding-left: 15px; padding-right: 15px; clear: both;}
		body .erase {display: none;}
		body .break {width: 100%!important; display: table-cell; margin:0; padding-bottom: 10px!important;}
}</style>

</head>
<!--Contenido del correo-->
<body style='margin: 0; padding: 0;'>

<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" class="full" bgcolor="#f3f7f8" style="background-color: #f3f7f8;">
	<tbody><tr>
		<td align="center">
						
			<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
				<tbody><tr>
					<td width="100%" valign="middle" class="logo" align="center">
					
						<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" style="text-align: center; border-collapse: collapse;" class="fullCenter">
							<tbody><tr>
								<td width="450" height="50"></td>
							</tr>
						</tbody></table>
						<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="full" bgcolor="#ffffff" style="-webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; -moz-box-shadow:0 0 10px #dedede; -webkit-box-shadow:0 0 10px #dedede; box-shadow:0 0 10px #dedede; background-color: #ffffff;">
							<tbody><tr>
								<td width="450" align="center">
									<!--Imagen de cabezera-->                      
									<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="full">
										<tbody><tr>
											<td width="450" valign="middle" align="center">
											
												<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" style="text-align: center; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; border-top-left-radius: 5px; border-top-right-radius: 5px;" class="fullCenter">
													<tbody><tr>
														<td width="450" class="full-size" style="line-height: 1px; border-top-left-radius: 5px; border-top-right-radius: 5px;">
															<a href="#"><img src="https://raw.githubusercontent.com/Seeeck/TurismoRealProject/pre-main/FotosTesteo/empty-living-room-with-blue-sofa-plants-table-empty-white-wall-background-3d-rendering_41470-1778.jpg" editable="true" alt="" border="0" width="100%" height="auto" class="hover toModifyImage"></a>
														</td>
													</tr>
												</tbody></table>
												
											</td>
										</tr>
									</tbody></table>
							
									<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
										<tbody><tr>
											<td width="450" valign="middle" align="center" height="40">
											</td>
										</tr>
									</tbody></table>
									<!--Contenido -->                        
                        			<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
										<tbody><tr>
											<td width="450" valign="middle" align="center" height="30" style="font-size: 1px; line-height: 1px;">&nbsp;</td>
										</tr>
									</tbody></table>
                        
									<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
										<tbody><tr>
											<td width="450" valign="middle" align="center">
									
												<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" style="text-align: center; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;" class="fullCenter">
													<tbody><tr>
														<td valign="middle" width="450" style="text-align: left; font-family: Helvetica, Arial, sans-serif, 'Open Sans'; font-size: 14px; color: #777e86; line-height: 24px;" class="fullCenter">
															¡Hola! {{nombre}} {{apellido}}
															<br>
															Su Check-In digital fue registrado exitosamente y puedes verlo o descargar desde su perfil en nuestra pagina
															<br>
															¡Gracias por confiar en nosotros! 
														</td>
													</tr>
												</tbody></table>
									
											</td>
										</tr>
									</tbody></table>
									
									<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
										<tbody><tr>
											<td width="450" valign="middle" align="center" height="30">
											</td>
										</tr>
									</tbody></table>
									<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
										<tbody><tr>
											<td width="450" valign="middle" align="center" height="50">
											</td>
										</tr>
									</tbody></table>
									
                              	</td>
							</tr>
						</tbody></table>
						<!-- footer-->
						<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="mobile">
							<tbody><tr>
								<td width="450" valign="middle" align="center" height="30">
								</td>
							</tr>
						</tbody></table>
						
						<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" class="full">
							<tbody><tr>
								<td style="font-family: Helvetica, Arial, sans-serif, 'Open Sans'; font-size: 12px; color: #a9a9a9; line-height: 24px;" align="center">
									Turismo Real 2022
									<br>
									Todos los derechos reservado
								</td>
							</tr>
							<tr>
								<td width="450" height="5" style="font-size: 1px; line-height: 1px;">&nbsp;</td>
							</tr>
						</tbody></table>
						
						<table width="450" border="0" cellpadding="0" cellspacing="0" align="center" style="text-align: center; border-collapse: collapse;" class="fullCenter">
							<tbody><tr>
								<td width="450" height="50"></td>
							</tr>
						</tbody></table>		
					</td>
				</tr>
			</tbody></table>
		</td>
	</tr>
</tbody></table>